INSERT INTO frutas (id, nombre, cantidad, color) VALUES (1, "Agraz", 1, "Morado");
INSERT INTO frutas (id, nombre, cantidad, color) VALUES (2, "Durazno", 3, "Amarillo");
INSERT INTO frutas (id, nombre, cantidad, color) VALUES (3, "Freijoa", 3, "Verde");
INSERT INTO frutas (id, nombre, cantidad, color) VALUES (4, "Fresa", 12, "Roja");
INSERT INTO frutas (id, nombre, cantidad, color) VALUES (5, "Mora", 9, "Morado");
INSERT INTO frutas (id, nombre, cantidad, color) VALUES (6, "Pera", 2, "Verde");
INSERT INTO carnes (id, nombre, cantidad, animal, peludo) VALUES (1, "Filete", 10, "Cerdo", 1);
INSERT INTO carnes (id, nombre, cantidad, animal, peludo) VALUES (2, "Palmito", 1000, "Cangrejo", 0);
INSERT INTO carnes (id, nombre, cantidad, animal, peludo) VALUES (3, "Pierna", 25, "Pollo", 0);
INSERT INTO carnes (id, nombre, cantidad, animal, peludo) VALUES (4, "Tenaza", 100, "Cangrejo", 0);
INSERT INTO carnes (id, nombre, cantidad, animal, peludo) VALUES (5, "Higado", 100, "Res", 1);
INSERT INTO responsables (id, username, nombre) VALUES (1, "jvalde", "Juan Valdez");
INSERT INTO responsables (id, username, nombre) VALUES (2, "croja", "Carolina Rojas");
INSERT INTO responsables (id, username, nombre) VALUES (3, "opere", "Oscar Perez");
INSERT INTO inventario (id, nombre, fecha, producto, responsable) VALUES (1, "Viceras", "2011-12-15", "Higado", "Juan Valdez");
INSERT INTO inventario (id, nombre, fecha, producto, responsable) VALUES (2, "Otros", "2013-01-15", "Higado", "Carolina Rojas");
INSERT INTO inventario (id, nombre, fecha, producto, responsable) VALUES (3, "Otros", "2015-12-15", "Pierna", "Carolina Rojas");
INSERT INTO inventario (id, nombre, fecha, producto, responsable) VALUES (4, "Frutas", "2010-12-19", "Agraz", "Juan Valdez");
INSERT INTO inventario (id, nombre, fecha, producto, responsable) VALUES (5, "Carnes", "2010-12-15", "Filete", "Oscar Perez");
INSERT INTO inventario (id, nombre, fecha, producto, responsable) VALUES (6, "Frutas", "2010-12-15", "Freijoa", "Juan Valdez");
INSERT INTO inventario (id, nombre, fecha, producto, responsable) VALUES (7, "Frutas", "2010-12-15", "Mora", "Juan Valdez");
INSERT INTO inventario (id, nombre, fecha, producto, responsable) VALUES (8, "Frutas", "2010-12-15", "Fresa", "Juan Valdez");
INSERT INTO inventario (id, nombre, fecha, producto, responsable) VALUES (9, "Frutas", "2010-12-13", "Pera", "Juan Valdez");
INSERT INTO inventario (id, nombre, fecha, producto, responsable) VALUES (10, "Otros", "2010-02-15", "Palmito", "Carolina Rojas");
INSERT INTO inventario (id, nombre, fecha, producto, responsable) VALUES (11, "Otros", "2010-02-15", "Tenaza", "Carolina Rojas");
