DROP SCHEMA db_meat;
CREATE SCHEMA db_meat;
USE db_meat;
CREATE TABLE carnes(id INT NOT NULL PRIMARY KEY AUTO_INCREMENT, nombre VARCHAR(20) NOT NULL, cantidad VARCHAR(20) NOT NULL, animal VARCHAR(20) NOT NULL, peludo VARCHAR(20) NOT NULL);
SELECT * FROM carnes;
